site_name: WhisperRealtimeマニュアル
site_url: https://Akiya-Research-Institute.github.io/WhisperRealtime-Manual/
site_author: Kenji Asaba
site_description: OpenAIのWhisperモデルをベースとした、Unreal Engineで動く多言語対応のリアルタイム音声テキスト変換・アラインメントプラグイン「Whisper-Based Real-time Speech Recognition」の公式ドキュメント
copyright: Copyright &copy; 2023 Akiya Research Institute, Inc. All Rights Reserved

site_dir: ../docs/ja

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: M PLUS 1
    code: M PLUS 1 Code
  language: ja
  favicon: images/favicon.png
  logo: images/logo.png
  features:
    - navigation.instant
    - navigation.tracking    
    # - navigation.tabs
    - navigation.sections
    # - navigation.expand
    # - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    
extra:
  alternate:
    - name: English
      link: /WhisperRealtime-Manual/en/ 
      lang: en
    - name: 日本語
      link: /WhisperRealtime-Manual/ja/
      lang: ja
  analytics:
    provider: google
    property: UA-2709176-10
  social:
    - icon: material/home
      link: https://vrlab.akiya-souken.co.jp/
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/channel/UC7t4amWNvquSy_ODcGZ4R0g
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/Akiya_Souken_VR
    - icon: fontawesome/brands/github 
      link: https://github.com/Akiya-Research-Institute
    - icon: material/store
      link: https://www.unrealengine.com/marketplace/ja/product/d293a6a427c94831888ca0f47bc5939b
  # generator: false

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details
  - footnotes

nav:
  - プラグイン:
    - index.md
    - system-requirement.md
    - install.md
    - modules.md
    - 使い方:
      - how-to-use-transcript.md
      - how-to-use-alignment-short.md
      - how-to-use-alignment-long.md
      - how-to-build-package.md
    - faq.md
    - changelog.md
  - デモプロジェクト:
    - demo-project-overview.md
